'\" t
.\" ** The above line should force tbl to be a preprocessor **
.\" Man page for recffmpeg
.\"
.\" Copyright (C), 2014, Leszek Lesner
.\"
.\" You may distribute under the terms of the GNU General Public
.\" License as specified in the file COPYING that comes with the main
.\" distribution.
.\"
.TH VOKOSCREEN 1 "2012-12-31" "recffmpeg Manual"
.SH NAME
recffmpeg \- simple screencast creator
.SH SYNOPSIS
Usage: \fBvokoscreen\fR
.SH DESCRIPTION
\fPrecffmpeg\fP is an easy to use screencast creator to record educational
videos, live recordings of browser, installation, videoconferences, etc.
It uses ffgtk functionality and also supports recording of audio (over pulseaudio or
alsa).
.SH FILES
Settings are stored under $XDG_CONFIG_HOME which is generally $HOME/.config. In this
documentation ~ is used.
.TP
.I ~/.config/Recffmpeg/Recffmpeg.conf
Configuration file stores audio settings, standard player, video path.
.TP
.I ~/.config/Recffmpeg/Recffmpeg.log
Log file stores information about the last execution of Recffmpeg.
.SH BUGS
Report bugs to <leszek@zevenos.com>.
